-- ─────────────────────────────────────────────────────────────────────
-- Aski IQ — Comprehensive Supabase RPC snapshot (2026-05)
--
-- Companion to:
--   SupabaseRPCs_Snapshot_2026-05-04.sql      (magic-link + tokens + jobs)
--   SupabaseMigration_QuoteAcceptance_Fix.sql (accept_quote_via_token)
--   SupabaseMigration_StageNormalization.sql  (latest accept_quote_via_token)
--   SupabaseMigration_EntityFirst_Slice2*.sql (auto_link triggers)
--   SupabaseMigration_TermsTemplates_SliceA.sql (bump_terms_template_version)
--   SupabaseMigration_QuoteApprovals_Slice5.sql (fn_quote_approvals_touch_updated_at)
--
-- WHAT'S IN THIS FILE
-- Auth/onboarding, role helpers, AI module, integrations, utility
-- triggers, maintenance — every public-schema function NOT covered
-- by the migration files above. Generated by snapshotting from prod;
-- copy-paste any of these into a new migration if you need to fix
-- one. DO NOT run this whole file as a migration — `CREATE OR REPLACE`
-- on stable functions is fine, but it'd be redundant churn.
--
-- WHAT'S NOT IN THIS FILE
-- 27 sample-data marker triggers (`fn_*_lock_sample_marker`). They
-- all share the same trivial shape — block UPDATE of `is_sample_data`
-- and friends — and there's nothing to gain from snapshotting
-- boilerplate. They'd be regenerated from a single template if ever
-- needed.
--
-- ─────────────────────────────────────────────────────────────────────
-- KNOWN ISSUES SURFACED DURING THIS SNAPSHOT PASS
-- ─────────────────────────────────────────────────────────────────────
-- 🔴 ROLE NAME CASING INCONSISTENCY
-- The iOS UserRole enum's raw values are snake_case (e.g.
-- `'office_admin'`, `'project_manager'`). Most SQL helpers correctly
-- compare against snake_case, but several use camelCase:
--
--   _require_company_admin() — checks against 'officeAdmin'  ❌
--   is_estimating_admin()    — checks against 'office_admin' ✅
--   is_field_role()          — uses get_my_role() (correct)  ✅
--   is_financial_admin()     — checks against 'officeAdmin'  ❌
--   is_foreman_or_above()    — checks against 'officeAdmin', 'projectManager' ❌
--   is_manager_or_above()    — uses get_my_role() (correct)  ✅
--   is_safety_admin()        — checks against 'safetyAdvisor', 'officeAdmin' ❌
--   set_company_ai_prompt()  — checks against 'officeAdmin'  ❌
--
-- iOS sends roles in snake_case. Any RLS policy or RPC using the
-- broken helpers (`is_financial_admin`, `is_foreman_or_above`,
-- `is_safety_admin`, `_require_company_admin`, `set_company_ai_prompt`)
-- silently FAILS for office_admin / project_manager / safety_advisor
-- users. This is a defect — those users get the "Not authenticated"
-- or "Admin role required" error even when their role should permit
-- the action.
--
-- Also: 'owner' is referenced in the helpers but doesn't exist in
-- the iOS UserRole enum (executive is the closest analog). Vestigial
-- from an older version.
--
-- FIX (separate migration, not in this file):
--   • Standardize all helpers on snake_case raw values
--   • Drop 'owner' references (or add it to UserRole if real)
--
-- ─────────────────────────────────────────────────────────────────────


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- AUTH / ONBOARDING
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Trigger that fires when auth.users gets a new row (via Supabase
-- signup). Creates the tenant company + the user's profile.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'auth', 'pg_temp'
AS $function$
DECLARE
    new_company_id uuid;
    company_name   text;
BEGIN
    company_name := COALESCE(
        NEW.raw_user_meta_data->>'company_name',
        'My Company'
    );

    INSERT INTO companies (name)
    VALUES (company_name)
    RETURNING id INTO new_company_id;

    INSERT INTO profiles (id, email, full_name, company_id)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
        new_company_id
    )
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
END;
$function$;

-- Manual setup path used by login when handle_new_user didn't fire.
CREATE OR REPLACE FUNCTION public.setup_new_user(p_full_name text, p_company_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id   uuid := auth.uid();
  v_company_id uuid;
BEGIN
  INSERT INTO companies (name, created_at)
  VALUES (p_company_name, now())
  RETURNING id INTO v_company_id;

  INSERT INTO profiles (id, email, full_name, role, is_active, company_id, created_at)
  SELECT v_user_id, email, p_full_name, 'manager', true, v_company_id, now()
  FROM auth.users WHERE id = v_user_id
  ON CONFLICT (id) DO UPDATE SET company_id = v_company_id, full_name = p_full_name;
END;
$function$;

-- Generates an 8-char invite code. Caller's company is the tenant.
CREATE OR REPLACE FUNCTION public.create_invite(p_role text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_company_id uuid;
  v_code       text;
BEGIN
  SELECT company_id INTO v_company_id FROM profiles WHERE id = auth.uid();
  IF NOT FOUND THEN RAISE EXCEPTION 'Profile not found'; END IF;
  v_code := upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  INSERT INTO invites (company_id, role, code, created_by)
  VALUES (v_company_id, p_role, v_code, auth.uid());
  RETURN v_code;
END;
$function$;

-- Consumes an invite code; sets up the new user's profile.
CREATE OR REPLACE FUNCTION public.use_invite(p_code text, p_full_name text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_invite  invites%ROWTYPE;
  v_user_id uuid := auth.uid();
BEGIN
  SELECT * INTO v_invite FROM invites
  WHERE code = upper(trim(p_code)) AND used_at IS NULL AND expires_at > now();
  IF NOT FOUND THEN RAISE EXCEPTION 'Invalid or expired invite code'; END IF;

  INSERT INTO profiles (id, email, full_name, role, is_active, company_id, created_at)
  SELECT v_user_id, email, p_full_name, v_invite.role, true, v_invite.company_id, now()
  FROM auth.users WHERE id = v_user_id
  ON CONFLICT (id) DO UPDATE SET
    company_id = v_invite.company_id,
    role       = v_invite.role,
    full_name  = p_full_name,
    is_active  = true;

  UPDATE invites SET used_by = v_user_id, used_at = now() WHERE id = v_invite.id;
  RETURN v_invite.role;
END;
$function$;

-- Admin gate used by token-mint + AI-config functions. Note: checks
-- against 'officeAdmin' (camelCase) which is INCONSISTENT with iOS
-- UserRole raw values (snake_case 'office_admin'). See "KNOWN ISSUES"
-- header above. Office admin users currently fail this check.
CREATE OR REPLACE FUNCTION public._require_company_admin()
RETURNS TABLE(user_id uuid, company_id uuid, role text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id    uuid := auth.uid();
  v_company_id uuid;
  v_role       text;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;
  SELECT p.company_id, p.role INTO v_company_id, v_role
  FROM public.profiles p
  WHERE p.id = v_user_id;
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'No profile / company for caller' USING ERRCODE = '42501';
  END IF;
  IF v_role NOT IN ('owner', 'executive', 'manager', 'officeAdmin') THEN
    RAISE EXCEPTION 'Admin role required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY SELECT v_user_id, v_company_id, v_role;
END $function$;

CREATE OR REPLACE FUNCTION public.get_my_company_id()
RETURNS uuid
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
    SELECT company_id FROM profiles WHERE id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'auth', 'pg_temp'
AS $function$
  select role from profiles where id = auth.uid()
$function$;

-- Returns admin emails for a company. Used by EmailService bridge
-- code on the server. Uses camelCase 'officeAdmin' — see KNOWN ISSUES.
CREATE OR REPLACE FUNCTION public.get_company_admin_emails(p_company_id uuid)
RETURNS TABLE(email text, full_name text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  RETURN QUERY
  SELECT p.email, p.full_name
  FROM public.profiles p
  WHERE p.company_id = p_company_id
    AND p.role IN ('owner', 'executive', 'manager', 'officeAdmin')
    AND p.is_active = true
    AND p.deleted_at IS NULL;
END $function$;

CREATE OR REPLACE FUNCTION public.ensure_company_settings(p_company_id uuid)
RETURNS company_settings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
    v_caller_company uuid;
    v_row public.company_settings;
BEGIN
    SELECT company_id INTO v_caller_company
    FROM public.profiles
    WHERE id = auth.uid();
    IF v_caller_company IS NULL OR v_caller_company <> p_company_id THEN
        RAISE EXCEPTION 'caller is not a member of company %', p_company_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    SELECT * INTO v_row
    FROM public.company_settings
    WHERE company_id = p_company_id;
    IF FOUND THEN RETURN v_row; END IF;

    INSERT INTO public.company_settings (company_id, name)
    SELECT c.id, c.name FROM public.companies c WHERE c.id = p_company_id
    ON CONFLICT (company_id) DO NOTHING;

    SELECT * INTO v_row
    FROM public.company_settings
    WHERE company_id = p_company_id;
    RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ensure_company_email_settings(p_company_id uuid)
RETURNS company_email_settings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
    v_caller_company uuid;
    v_row public.company_email_settings;
    v_company_name   text;
    v_caller_email   text;
BEGIN
    SELECT company_id INTO v_caller_company
    FROM public.profiles WHERE id = auth.uid();
    IF v_caller_company IS NULL OR v_caller_company <> p_company_id THEN
        RAISE EXCEPTION 'caller is not a member of company %', p_company_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    SELECT * INTO v_row
    FROM public.company_email_settings WHERE company_id = p_company_id;
    IF FOUND THEN RETURN v_row; END IF;

    SELECT name INTO v_company_name FROM public.companies WHERE id = p_company_id;
    SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();

    INSERT INTO public.company_email_settings
        (company_id, from_name, reply_to_email, updated_by)
    VALUES
        (p_company_id,
         COALESCE(v_company_name, ''),
         COALESCE(v_caller_email, ''),
         auth.uid())
    ON CONFLICT (company_id) DO NOTHING;

    SELECT * INTO v_row
    FROM public.company_email_settings WHERE company_id = p_company_id;
    RETURN v_row;
END;
$function$;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- ROLE HELPERS (used by RLS policies + RPCs)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ✅ Correct (snake_case)
CREATE OR REPLACE FUNCTION public.is_estimating_admin()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT COALESCE(
    (SELECT role IN ('estimator',
                     'project_manager',
                     'office_admin',
                     'manager',
                     'executive',
                     'owner')
     FROM public.profiles WHERE id = auth.uid()),
    false
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_field_role()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'auth', 'pg_temp'
AS $function$
  select get_my_role() in ('field_worker','foreman')
$function$;

CREATE OR REPLACE FUNCTION public.is_manager_or_above()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'auth', 'pg_temp'
AS $function$
  select get_my_role() in ('manager','executive')
$function$;

-- ❌ Broken (camelCase) — see KNOWN ISSUES header
CREATE OR REPLACE FUNCTION public.is_financial_admin()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select coalesce(
    (select role in ('officeAdmin', 'manager', 'executive', 'owner')
     from profiles where id = auth.uid()),
    false
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_foreman_or_above()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select coalesce(
    (select role in ('foreman', 'projectManager', 'officeAdmin',
                     'manager', 'executive', 'owner')
     from profiles where id = auth.uid()),
    false
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_safety_admin()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select coalesce(
    (select role in ('safetyAdvisor', 'officeAdmin', 'manager', 'executive', 'owner')
     from profiles where id = auth.uid()),
    false
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_not_client()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select coalesce(
    (select role <> 'client'
     from profiles where id = auth.uid()),
    false
  );
$function$;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- WORKFLOW HELPERS
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- BEFORE INSERT trigger that fills NEW.company_id from caller's profile
-- when the iOS app forgets. Used on every multi-tenant table.
CREATE OR REPLACE FUNCTION public.stamp_company_id()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    IF NEW.company_id IS NULL THEN
        NEW.company_id := get_my_company_id();
    END IF;
    RETURN NEW;
END;
$function$;

-- Sample-data nuke. Executive only. Wipes every is_sample_data row
-- in batch order so FKs unwind cleanly.
CREATE OR REPLACE FUNCTION public.clear_sample_data(p_company_id uuid, p_batch_id uuid, p_confirm_phrase text)
RETURNS TABLE(table_name text, rows_deleted bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
    v_caller_role     TEXT;
    v_per_table_count BIGINT;
    v_delete_order CONSTANT TEXT[] := ARRAY[
        'lien_waivers','invoices','change_orders','rfis','daily_job_reports',
        'exception_logs','timesheet_entries','schedule_entries','incidents',
        'form_submissions','crm_attachments','crm_activities','crm_tasks',
        'handoff_checklists','crm_opportunities','crm_contacts',
        'purchase_orders','material_requests','subcontracts','subcontractors',
        'project_budgets','documents','material_sales','quotes','estimates',
        'contracts','projects','crews','equipment','certificates',
        'client_pricings','product_services','suppliers','clients'
    ];
    v_tbl TEXT;
BEGIN
    IF p_confirm_phrase IS DISTINCT FROM 'DELETE SAMPLE DATA' THEN
        RAISE EXCEPTION 'confirmation phrase mismatch'
            USING HINT = 'caller must pass DELETE SAMPLE DATA exactly';
    END IF;

    SELECT role INTO v_caller_role
    FROM employees
    WHERE id = auth.uid() AND company_id = p_company_id AND COALESCE(is_active, TRUE);
    IF v_caller_role IS NULL OR v_caller_role <> 'executive' THEN
        RAISE EXCEPTION 'caller % is not an executive of company %', auth.uid(), p_company_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    PERFORM set_config('aski.sample_reset_in_progress', 'true', true);
    PERFORM pg_advisory_xact_lock(hashtext('sample_data_' || p_company_id::text));

    FOREACH v_tbl IN ARRAY v_delete_order LOOP
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = v_tbl
        ) THEN CONTINUE; END IF;

        EXECUTE format($f$
            WITH d AS (
              DELETE FROM %I
              WHERE company_id = $1
                AND is_sample_data = TRUE
                AND sample_data_batch_id = $2
              RETURNING 1
            )
            SELECT count(*) FROM d;
        $f$, v_tbl) INTO v_per_table_count USING p_company_id, p_batch_id;

        table_name   := v_tbl;
        rows_deleted := v_per_table_count;
        RETURN NEXT;
    END LOOP;

    INSERT INTO workflow_log (rule_id, rule_name, title, body, company_id)
    VALUES (
        gen_random_uuid(),
        'Sample Data Reset',
        format('Sample data batch %s cleared (DEV)', p_batch_id),
        format('Cleared by %s', auth.uid()),
        p_company_id
    );
END $function$;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- UTILITY TRIGGERS — generic touch-updated_at variants
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_quotes_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_crm_opportunity_timestamp()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_create_company_settings()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    INSERT INTO public.company_settings (company_id, name)
    VALUES (NEW.id, NEW.name)
    ON CONFLICT (company_id) DO NOTHING;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_create_company_email_settings()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    INSERT INTO public.company_email_settings (company_id, from_name)
    VALUES (NEW.id, NEW.name)
    ON CONFLICT (company_id) DO NOTHING;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_touch_company_email_settings()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN NEW.updated_at := now(); RETURN NEW; END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_sync_company_name()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    IF NEW.name IS DISTINCT FROM OLD.name AND NEW.name IS NOT NULL THEN
        UPDATE public.companies
        SET name = NEW.name
        WHERE id = NEW.company_id;
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$function$;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- AI MODULE
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- BYOK Anthropic key — stored in Supabase Vault, fetched via this proxy.
-- Caller is the Edge Function relaying iOS requests to Anthropic.
CREATE OR REPLACE FUNCTION public.get_company_ai_key_for_proxy(p_company_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'vault'
AS $function$
DECLARE
  v_secret_id uuid;
  v_value     text;
BEGIN
  SELECT anthropic_api_key_vault_id INTO v_secret_id
  FROM public.companies WHERE id = p_company_id;
  IF v_secret_id IS NULL THEN RETURN NULL; END IF;

  SELECT decrypted_secret INTO v_value
  FROM vault.decrypted_secrets WHERE id = v_secret_id;

  RETURN v_value;
END $function$;

CREATE OR REPLACE FUNCTION public.get_company_ai_key_status()
RETURNS TABLE(is_set boolean, updated_at timestamp with time zone, updated_by_name text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id    uuid := auth.uid();
  v_company_id uuid;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;
  SELECT company_id INTO v_company_id
  FROM public.profiles WHERE id = v_user_id;
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'No profile / company for caller' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    (c.anthropic_api_key IS NOT NULL),
    c.anthropic_api_key_updated_at,
    p.full_name
  FROM public.companies c
  LEFT JOIN public.profiles p ON p.id = c.anthropic_api_key_updated_by
  WHERE c.id = v_company_id;
END $function$;

-- Sets per-company Anthropic API key. Empty input revokes.
-- Goes through Vault for at-rest encryption.
CREATE OR REPLACE FUNCTION public.set_company_ai_key(p_key text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_admin           record;
  v_clean           text;
  v_existing_id     uuid;
  v_company_name    text;
BEGIN
  SELECT * INTO v_admin FROM public._require_company_admin();
  v_clean := btrim(coalesce(p_key, ''));

  SELECT anthropic_api_key_vault_id, name
    INTO v_existing_id, v_company_name
  FROM public.companies WHERE id = v_admin.company_id;

  IF v_clean = '' THEN
    IF v_existing_id IS NOT NULL THEN
      DELETE FROM vault.secrets WHERE id = v_existing_id;
    END IF;
    UPDATE public.companies
       SET anthropic_api_key_vault_id     = NULL,
           anthropic_api_key_updated_at   = now(),
           anthropic_api_key_updated_by   = v_admin.user_id
     WHERE id = v_admin.company_id;
    RETURN;
  END IF;

  IF v_clean NOT LIKE 'sk-ant-%' THEN
    RAISE EXCEPTION 'Key does not look like an Anthropic API key (expected prefix sk-ant-)'
      USING ERRCODE = '22023';
  END IF;

  IF v_existing_id IS NOT NULL THEN
    PERFORM vault.update_secret(v_existing_id, v_clean);
    UPDATE public.companies
       SET anthropic_api_key_updated_at = now(),
           anthropic_api_key_updated_by = v_admin.user_id
     WHERE id = v_admin.company_id;
  ELSE
    UPDATE public.companies
       SET anthropic_api_key_vault_id = vault.create_secret(
              v_clean,
              'anthropic_api_key_' || v_admin.company_id::text,
              'Per-company Anthropic API key (BYOK) for ' || v_company_name
            ),
           anthropic_api_key_updated_at = now(),
           anthropic_api_key_updated_by = v_admin.user_id
     WHERE id = v_admin.company_id;
  END IF;
END $function$;

CREATE OR REPLACE FUNCTION public.set_company_ai_limits(
  p_daily_token_limit bigint,
  p_monthly_token_limit bigint,
  p_daily_cost_limit_cents bigint,
  p_monthly_cost_limit_cents bigint,
  p_pause_when_exceeded boolean,
  p_admin_notification_enabled boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_admin record;
BEGIN
  SELECT * INTO v_admin FROM public._require_company_admin();
  UPDATE public.companies
     SET daily_token_limit              = p_daily_token_limit,
         monthly_token_limit            = p_monthly_token_limit,
         daily_cost_limit_cents         = p_daily_cost_limit_cents,
         monthly_cost_limit_cents       = p_monthly_cost_limit_cents,
         ai_pause_when_exceeded         = p_pause_when_exceeded,
         ai_admin_notification_enabled  = p_admin_notification_enabled
   WHERE id = v_admin.company_id;
END $function$;

-- See KNOWN ISSUES — uses camelCase 'officeAdmin' which iOS won't pass.
CREATE OR REPLACE FUNCTION public.set_company_ai_prompt(p_surface text, p_prompt text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_company uuid;
  v_role    text;
begin
  select p.company_id, p.role
    into v_company, v_role
    from profiles p
   where p.id = auth.uid();

  if v_company is null then
    raise exception 'No tenant for caller';
  end if;
  if v_role not in ('officeAdmin', 'manager', 'executive', 'owner') then
    raise exception 'Admin role required to change AI prompts'
      using errcode = '42501';
  end if;
  if p_surface not in ('chat', 'contract_review', 'contract_diff', 'crm_brief') then
    raise exception 'Unknown AI surface: %', p_surface;
  end if;

  if coalesce(trim(p_prompt), '') = '' then
    update companies
       set ai_prompt_overrides = ai_prompt_overrides - p_surface,
           updated_at          = now()
     where id = v_company;
  else
    update companies
       set ai_prompt_overrides = ai_prompt_overrides
                                  || jsonb_build_object(p_surface, p_prompt),
           updated_at          = now()
     where id = v_company;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_company_ai_limits()
RETURNS TABLE(
  daily_token_limit bigint, monthly_token_limit bigint,
  daily_cost_limit_cents bigint, monthly_cost_limit_cents bigint,
  ai_pause_when_exceeded boolean, ai_admin_notification_enabled boolean,
  today_request_count bigint, today_input_tokens bigint,
  today_output_tokens bigint, today_cost_cents bigint,
  month_request_count bigint, month_input_tokens bigint,
  month_output_tokens bigint, month_cost_cents bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id    uuid := auth.uid();
  v_company_id uuid;
  v_today      date := current_date;
  v_month_start date := date_trunc('month', current_date)::date;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;
  SELECT p.company_id INTO v_company_id
  FROM public.profiles p WHERE p.id = v_user_id;
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'No profile / company for caller' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    c.daily_token_limit,
    c.monthly_token_limit,
    c.daily_cost_limit_cents,
    c.monthly_cost_limit_cents,
    c.ai_pause_when_exceeded,
    c.ai_admin_notification_enabled,
    coalesce((SELECT sum(u.request_count)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date = v_today), 0),
    coalesce((SELECT sum(u.input_tokens)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date = v_today), 0),
    coalesce((SELECT sum(u.output_tokens)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date = v_today), 0),
    coalesce((SELECT sum(u.cost_cents)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date = v_today), 0),
    coalesce((SELECT sum(u.request_count)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date >= v_month_start), 0),
    coalesce((SELECT sum(u.input_tokens)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date >= v_month_start), 0),
    coalesce((SELECT sum(u.output_tokens)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date >= v_month_start), 0),
    coalesce((SELECT sum(u.cost_cents)::bigint FROM public.ai_usage_daily u
              WHERE u.company_id = c.id AND u.user_id IS NULL AND u.usage_date >= v_month_start), 0)
  FROM public.companies c
  WHERE c.id = v_company_id;
END $function$;

CREATE OR REPLACE FUNCTION public.get_my_company_ai_prompts()
RETURNS jsonb
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select coalesce(c.ai_prompt_overrides, '{}'::jsonb)
    from companies c
   where c.id = (select company_id from profiles where id = auth.uid());
$function$;

-- Cross-tenant guard: admin can only adjust users in their own company.
CREATE OR REPLACE FUNCTION public.set_user_ai_limits(
  p_user_id uuid, p_requests_per_minute integer, p_tokens_per_day bigint,
  p_blocked_until timestamp with time zone, p_blocked_reason text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_admin            record;
  v_target_company   uuid;
BEGIN
  SELECT * INTO v_admin FROM public._require_company_admin();

  SELECT company_id INTO v_target_company FROM public.profiles WHERE id = p_user_id;
  IF v_target_company IS NULL THEN
    RAISE EXCEPTION 'Target user not found' USING ERRCODE = '42501';
  END IF;
  IF v_target_company <> v_admin.company_id THEN
    RAISE EXCEPTION 'Cannot modify users outside your company' USING ERRCODE = '42501';
  END IF;

  UPDATE public.profiles
     SET ai_requests_per_minute = p_requests_per_minute,
         ai_tokens_per_day      = p_tokens_per_day,
         ai_blocked_until       = p_blocked_until,
         ai_blocked_reason      = p_blocked_reason
   WHERE id = p_user_id;
END $function$;

-- AI usage rollup. Inserts both a per-(company,user) row AND a
-- per-company rollup row. ON CONFLICT updates the totals.
CREATE OR REPLACE FUNCTION public.record_ai_usage(
  p_company_id uuid, p_user_id uuid, p_model text,
  p_input_tokens bigint, p_output_tokens bigint, p_cost_cents bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_today date := current_date;
BEGIN
  INSERT INTO public.ai_usage_daily (
    company_id, user_id, usage_date, request_count,
    input_tokens, output_tokens, cost_cents,
    model_breakdown, updated_at
  ) VALUES (
    p_company_id, p_user_id, v_today, 1,
    p_input_tokens, p_output_tokens, p_cost_cents,
    jsonb_build_object(p_model, jsonb_build_object(
      'requests', 1,
      'input_tokens', p_input_tokens,
      'output_tokens', p_output_tokens,
      'cost_cents', p_cost_cents
    )),
    now()
  )
  ON CONFLICT (company_id, coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid), usage_date)
  DO UPDATE SET
    request_count   = public.ai_usage_daily.request_count + 1,
    input_tokens    = public.ai_usage_daily.input_tokens  + EXCLUDED.input_tokens,
    output_tokens   = public.ai_usage_daily.output_tokens + EXCLUDED.output_tokens,
    cost_cents      = public.ai_usage_daily.cost_cents    + EXCLUDED.cost_cents,
    model_breakdown = public.ai_usage_daily.model_breakdown
                      || jsonb_build_object(p_model, jsonb_build_object(
                        'requests',
                          coalesce((public.ai_usage_daily.model_breakdown->p_model->>'requests')::int, 0) + 1,
                        'input_tokens',
                          coalesce((public.ai_usage_daily.model_breakdown->p_model->>'input_tokens')::bigint, 0) + EXCLUDED.input_tokens,
                        'output_tokens',
                          coalesce((public.ai_usage_daily.model_breakdown->p_model->>'output_tokens')::bigint, 0) + EXCLUDED.output_tokens,
                        'cost_cents',
                          coalesce((public.ai_usage_daily.model_breakdown->p_model->>'cost_cents')::bigint, 0) + EXCLUDED.cost_cents
                      )),
    updated_at = now();

  INSERT INTO public.ai_usage_daily (
    company_id, user_id, usage_date, request_count,
    input_tokens, output_tokens, cost_cents, updated_at
  ) VALUES (
    p_company_id, NULL, v_today, 1,
    p_input_tokens, p_output_tokens, p_cost_cents, now()
  )
  ON CONFLICT (company_id, coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid), usage_date)
  DO UPDATE SET
    request_count = public.ai_usage_daily.request_count + 1,
    input_tokens  = public.ai_usage_daily.input_tokens  + EXCLUDED.input_tokens,
    output_tokens = public.ai_usage_daily.output_tokens + EXCLUDED.output_tokens,
    cost_cents    = public.ai_usage_daily.cost_cents    + EXCLUDED.cost_cents,
    updated_at    = now();
END $function$;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- INTEGRATIONS — QuickBooks Online + Stripe
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CREATE OR REPLACE FUNCTION public.get_my_qbo_status()
RETURNS TABLE(realm_id text, is_active boolean, connected_at timestamp with time zone, last_synced_at timestamp with time zone, last_error text, access_valid boolean)
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select s.realm_id, s.is_active, s.connected_at, s.last_synced_at, s.last_error, s.access_valid
    from qbo_connection_status s
   where s.company_id = (select company_id from profiles where id = auth.uid());
$function$;

CREATE OR REPLACE FUNCTION public.get_my_qbo_entity_ids(p_table text)
RETURNS TABLE(aski_id uuid, qbo_id text, last_pushed_at timestamp with time zone)
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  select m.aski_id, m.qbo_id, m.last_pushed_at
    from qbo_entity_map m
   where m.company_id = (select company_id from profiles where id = auth.uid())
     and m.aski_table = p_table;
$function$;

-- Stripe webhook lands here. Idempotent on payment_intent_id.
-- Recomputes total_paid + balance_due from the payments JSONB array
-- so we don't drift if a prior write was incomplete.
CREATE OR REPLACE FUNCTION public.record_invoice_stripe_payment(
  p_invoice_id uuid, p_payment_intent_id text,
  p_amount numeric, p_currency text DEFAULT 'USD'::text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_invoice    invoices%rowtype;
  v_payments   jsonb;
  v_existing   jsonb;
  v_total_paid numeric := 0;
  v_balance    numeric;
  v_new_status text;
begin
  select * into v_invoice from invoices where id = p_invoice_id;
  if not found then
    raise exception 'Invoice % not found', p_invoice_id;
  end if;

  v_existing := coalesce(v_invoice.payments, '[]'::jsonb);
  if exists (
    select 1
    from jsonb_array_elements(v_existing) e
    where e->>'paymentIntentID' = p_payment_intent_id
       or e->>'externalReference' = p_payment_intent_id
  ) then
    return;
  end if;

  v_payments := v_existing || jsonb_build_array(jsonb_build_object(
    'id',                gen_random_uuid()::text,
    'amount',            p_amount,
    'paymentDate',       to_jsonb(now()),
    'method',            'stripe',
    'externalReference', p_payment_intent_id,
    'paymentIntentID',   p_payment_intent_id,
    'currency',          coalesce(p_currency, 'USD'),
    'notes',             case when p_amount < 0 then 'Stripe refund' else 'Stripe payment' end,
    'recordedBy',        'stripe-webhook',
    'recordedAt',        to_jsonb(now())
  ));

  select coalesce(sum((e->>'amount')::numeric), 0)
    into v_total_paid
    from jsonb_array_elements(v_payments) e;

  v_balance := coalesce(v_invoice.total, 0) - v_total_paid;

  if v_balance <= 0 then
    v_new_status := 'paid';
  elsif v_total_paid > 0 then
    v_new_status := 'partial';
  else
    if v_invoice.status in ('paid', 'partial') then
      v_new_status := 'sent';
    else
      v_new_status := v_invoice.status;
    end if;
  end if;

  update invoices
     set payments    = v_payments,
         total_paid  = v_total_paid,
         balance_due = v_balance,
         status      = v_new_status,
         paid_at     = case when v_new_status = 'paid' then now() else null end,
         updated_at  = now()
   where id = p_invoice_id;
end;
$function$;


-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- MAINTENANCE
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Run periodically (cron / Edge Function) to trim old workflow_log entries.
CREATE OR REPLACE FUNCTION public.purge_old_workflow_log(p_older_than_days integer DEFAULT 365)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_count integer;
begin
  delete from workflow_log
   where fired_at < now() - make_interval(days => p_older_than_days)
  returning 1 into v_count;
  return coalesce(v_count, 0);
end;
$function$;
